// lib/data.ts
// Data statis terpusat — nanti bisa diganti dengan fetch dari API/database

import type { Package, Testimonial, FAQ } from "@/types"

export const packages: Package[] = [
  {
    id: "pkg-reguler",
    slug: "reguler",
    name: "Paket Reguler",
    type: "reguler",
    price: "Rp 25.900.000",
    priceNum: 25900000,
    duration: "9 Hari",
    badge: null,
    highlight: false,
    airline: "Garuda Indonesia",
    hotelMecca: "Hotel Bintang 4 dekat Masjidil Haram",
    hotelMadinah: "Hotel Bintang 4 dekat Masjid Nabawi",
    includes: [
      "Tiket PP Garuda Indonesia",
      "Hotel Bintang 4 (Makkah & Madinah)",
      "Visa Umroh & Handling",
      "Makan 3x Sehari",
      "Pembimbing Umroh Bersertifikat",
      "Perlengkapan Umroh Lengkap",
      "Asuransi Perjalanan",
      "Manasik Online & Offline",
    ],
    itinerary: [
      { day: 1, title: "Keberangkatan Jakarta", activities: ["Check-in bandara", "Penerbangan menuju Madinah"] },
      { day: 2, title: "Tiba di Madinah", activities: ["Check-in hotel", "Shalat Arbain di Masjid Nabawi"] },
      { day: 3, title: "Ziarah Madinah", activities: ["Raudhah", "Makam Baqi", "Masjid Quba"] },
      { day: 4, title: "Madinah - Makkah", activities: ["Perjalanan ke Makkah", "Umroh pertama"] },
      { day: 5, title: "Ibadah di Makkah", activities: ["Tawaf sunnah", "Ziarah Makkah"] },
      { day: 6, title: "Ziarah Makkah", activities: ["Jabal Nur", "Jabal Tsur", "Mina & Arafah"] },
      { day: 7, title: "Ibadah Bebas", activities: ["Tawaf & Sa'i sunnah", "Belanja oleh-oleh"] },
      { day: 8, title: "Makkah - Jeddah", activities: ["City tour Jeddah", "Masjid Terapung"] },
      { day: 9, title: "Kepulangan", activities: ["Penerbangan pulang ke Jakarta"] },
    ],
  },
  {
    id: "pkg-business",
    slug: "business",
    name: "Paket Business",
    type: "business",
    price: "Rp 35.500.000",
    priceNum: 35500000,
    duration: "12 Hari",
    badge: "Paling Populer",
    highlight: true,
    airline: "Saudia Airlines",
    hotelMecca: "Hotel Bintang 5 dekat Masjidil Haram",
    hotelMadinah: "Hotel Bintang 5 dekat Masjid Nabawi",
    includes: [
      "Tiket PP Saudia Airlines",
      "Hotel Bintang 5 (Makkah & Madinah)",
      "Visa Umroh & Handling",
      "Makan 3x Sehari (Prasmanan)",
      "Pembimbing Umroh Senior",
      "Perlengkapan Umroh Premium",
      "Asuransi Jiwa & Kesehatan",
      "Manasik Eksklusif + Modul",
      "Ziarah Lengkap Makkah–Madinah",
      "Airport Fast Track Service",
    ],
  },
  {
    id: "pkg-vip",
    slug: "vip",
    name: "Paket VIP",
    type: "vip",
    price: "Rp 55.000.000",
    priceNum: 55000000,
    duration: "15 Hari",
    badge: "Eksklusif",
    highlight: false,
    airline: "Saudia Airlines (Business Class)",
    hotelMecca: "Hotel Bintang 5 Tower Zamzam",
    hotelMadinah: "Hotel Bintang 5 Angsana Madinah",
    includes: [
      "Tiket PP Business Class",
      "Hotel Bintang 5 Premium (Makkah & Madinah)",
      "Visa Umroh & Handling",
      "Semua Makan (Fine Dining)",
      "Pembimbing Umroh Pribadi",
      "Perlengkapan Umroh Mewah",
      "Asuransi Komprehensif",
      "Manasik VIP + Kitab",
      "Ziarah Lengkap + Private Tour",
      "Airport VIP Lounge",
      "Transportasi Pribadi",
    ],
  },
]

export const testimonials: Testimonial[] = [
  {
    id: "t1",
    name: "Hj. Fatimah Zahra",
    location: "Jakarta Selatan",
    rating: 5,
    text: "Alhamdulillah, perjalanan umroh bersama Umrohinaja sangat berkesan. Pelayanan prima dari awal hingga akhir. Pembimbing kami, Ustaz Ahmad, sangat sabar dan berpengetahuan luas.",
    package: "Paket Business",
    initials: "FZ",
    bg: "#1F4D3A",
  },
  {
    id: "t2",
    name: "Bpk. Muhammad Rizky",
    location: "Surabaya",
    rating: 5,
    text: "Ini umroh kedua saya, dan pertama kalinya bersama Umrohinaja. Perbedaannya sangat terasa! Hotel lebih dekat, makanan lebih baik, dan pembimbing lebih profesional.",
    package: "Paket VIP",
    initials: "MR",
    bg: "#2F6B52",
  },
  {
    id: "t3",
    name: "Ibu Siti Rahayu",
    location: "Bandung",
    rating: 5,
    text: "Sebagai ibu yang pertama kali umroh, saya sangat terbantu dengan pelayanan Umrohinaja yang detail dan penuh perhatian. Terima kasih telah membuat ibadah saya begitu lancar.",
    package: "Paket Reguler",
    initials: "SR",
    bg: "#3A8464",
  },
  {
    id: "t4",
    name: "Ust. Ahmad Fauzi",
    location: "Yogyakarta",
    rating: 5,
    text: "Saya rekomendasikan Umrohinaja kepada seluruh jamaah di masjid kami. Amanah, profesional, dan harga sesuai kualitas. Sudah 3 keluarga dari masjid kami bergabung.",
    package: "Paket Business",
    initials: "AF",
    bg: "#1F4D3A",
  },
]

export const faqs: FAQ[] = [
  {
    q: "Apa saja yang termasuk dalam paket umroh Umrohinaja?",
    a: "Setiap paket kami sudah mencakup tiket pesawat PP, akomodasi hotel sesuai paket, transportasi selama di Arab Saudi, konsumsi 3x sehari, visa umroh dan biaya handling, perlengkapan umroh, pembimbing ibadah bersertifikat, dan asuransi perjalanan.",
  },
  {
    q: "Bagaimana cara mendaftar paket umroh?",
    a: "Proses pendaftaran sangat mudah: (1) Pilih paket yang sesuai, (2) Hubungi kami via WhatsApp atau datang ke kantor, (3) Lengkapi dokumen persyaratan, (4) Bayar DP minimal 30%, (5) Ikuti manasik umroh yang kami selenggarakan.",
  },
  {
    q: "Berapa lama proses pengurusan visa umroh?",
    a: "Proses pengurusan visa umroh biasanya membutuhkan waktu 7–14 hari kerja setelah dokumen lengkap diterima. Kami sarankan mendaftar minimal 2 bulan sebelum jadwal keberangkatan.",
  },
  {
    q: "Apakah ada layanan khusus untuk jamaah lansia atau berkebutuhan khusus?",
    a: "Ya, kami menyediakan layanan pendampingan khusus untuk jamaah lansia dan berkebutuhan khusus. Silakan informasikan kondisi kesehatan dan kebutuhan spesifik saat mendaftar.",
  },
  {
    q: "Bagaimana sistem pembayaran dan cicilan?",
    a: "DP minimal 30% saat pendaftaran, pelunasan H-30 sebelum keberangkatan. Untuk paket tertentu, tersedia program cicilan tanpa bunga hingga 12 bulan bekerja sama dengan mitra bank.",
  },
  {
    q: "Apa yang harus dilakukan jika ada keadaan darurat saat di Tanah Suci?",
    a: "Tim kami siap 24 jam di lokasi selama keberangkatan. Setiap jamaah mendapatkan nomor kontak darurat pembimbing dan koordinator lokal, serta kontak RS Indonesia di Makkah dan Madinah.",
  },
]